export default [
  {
    id: 1,
    title: 'Orange',
    image: '🍊',
    price: 1099,
    measure: '/5 kg',
    category: 1,
    sale: false,
  },
  {
    id: 2,
    title: 'Kokosnüsse',
    image: '🥥',
    price: 1499,
    measure: '/2 kg',
    category: 3,
    sale: false,
  },
  {
    id: 3,
    title: 'Auberginen',
    image: '🍆',
    price: 999,
    measure: '/3 kg',
    category: 2,
    sale: false,
  },
  {
    id: 4,
    title: 'Tomaten',
    image: '🍅',
    price: 510,
    measure: '/1 kg',
    category: 2,
    sale: true,
  },
  {
    id: 5,
    title: 'Birnen',
    image: '🍐',
    price: 3999,
    measure: '/15 kg',
    category: 1,
    sale: false,
  },
  {
    id: 6,
    title: 'Erdnüsse',
    image: '🥜',
    price: 3999,
    measure: '/20 kg',
    category: 3,
    sale: false,
  },
  {
    id: 7,
    title: 'Kirschen',
    image: '🍒',
    price: 299,
    measure: '/300 g',
    category: 1,
    sale: true,
  },
  {
    id: 8,
    title: 'Kartoffeln',
    image: '🥔',
    price: 599,
    measure: '/7 kg',
    category: 2,
    sale: false,
  },
  {
    id: 9,
    title: 'Champignons',
    image: '🍄',
    price: 399,
    measure: '/100 g',
    category: 4,
    sale: true,
  },
  {
    id: 10,
    title: 'Zwiebeln',
    image: '🧅',
    price: 199,
    measure: '/1 kg',
    category: 2,
    sale: false,
  },
  {
    id: 11,
    title: 'Gurken',
    image: '🥒',
    price: 99,
    measure: '/500 g',
    category: 2,
    sale: false,
  },
  {
    id: 12,
    title: 'Salat',
    image: '🥬',
    price: 899,
    measure: '/2 kg',
    category: 2,
    sale: false,
  },
];

export const categories = [
  { categoryId: 1, name: 'Obst' },
  { categoryId: 2, name: 'Gemüse' },
  { categoryId: 3, name: 'Nüsse' },
  { categoryId: 4, name: 'Pilze' },
];
